### ISSUE TITLE
I dont see any code to persist account data and message data

### ISSUE THREAD

**Issue by Rishikesh01** [smartinrub/spring-xmpp-websocket-reactjs#6]
Is the application still in development?

**Comment by smartinrub** [comment]
@Rishikesh01 unfortunately it's not in development anymore. Not sure if I can help somehow. I'm just curious, are you using this for an open source project or for an organization?

**Comment by Rishikesh01** [comment]
Sorry for the late reply(didnt check my email)

> @Rishikesh01 unfortunately it's not in development anymore. Not sure if I can help somehow. I'm just curious, are you using this for an open source project or for an organization?

No i am not using your project as starter code for my project.
I am  working on a chat application  for which i was deciding the protocol to proceed with and XMPP being a popular protocol i was looking for an example how does smack+spring integrate and how do you actually modify the XMPP message structure and persist the message/user account info into database.

in general i was trying to understand how XMPP works.

So as a result i found your repo(if i found via your website)

**Comment by smartinrub** [comment]
@Rishikesh01 there is a XMPP [Spring integration](https://docs.spring.io/spring-integration/reference/html/xmpp.html) just in case you want to use it and I hope this repo is helpful

**Comment by Rishikesh01** [comment]
Yes thank you
